sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t regalme/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true regalme/docker-react npm run test